name: mlops Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud --quiet auth configure-docker asia-southeast2-docker.pkg.dev
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT }}

    - name: Build and push Docker image
      run: |
        docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/testdeployment/iris-mlops-app:latest .
        docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/testdeployment/iris-mlops-app:latest
